name: CI

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - feature/node_modules_cache
      - main

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  setup:
    # Name the Job
    name: setup
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        # 缓存node_modules
        # 优化ci安装依赖速度
        - uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'

        - name: install packages
          run: |
            yarn install
            node -v
  static-check:
    name: static check
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: eslint
        run: yarn lint
      - name: prettier
        run: |
          yarn prettier
          node -v
  unit-test:
    name: unit test
    runs-on: ubuntu-latest
    needs: [setup, static-check]
    steps:
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: unit-test
        run: |
          yarn test
          node -v
